import javax.swing.*;
import java.awt.*;
// import java.util.*;

import java.util.List;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import java.util.Random;

public class SimpleChatbot extends JFrame {
        private JTextArea chatArea;
        private JTextField inputField;

        private Map<String, List<String>> intents;

        public SimpleChatbot() {
                initializeIntents();

                setTitle("Simple Chatbot");
                setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                setSize(500, 400);
                setLocationRelativeTo(null);

                chatArea = new JTextArea();
                chatArea.setEditable(false);

                JScrollPane scrollPane = new JScrollPane(chatArea);

                inputField = new JTextField();
                JButton sendButton = new JButton("Send");
                sendButton.addActionListener(e -> processUserInput());

                setLayout(new BorderLayout());
                add(scrollPane, BorderLayout.CENTER);
                add(inputField, BorderLayout.SOUTH);
                add(sendButton, BorderLayout.EAST);

                setVisible(true);
        }

        private void initializeIntents() {
                intents = new HashMap<>();

                addIntent("greeting",
                                Arrays.asList("Hi",
                                                "How are you",
                                                "Are you there Jarvis?",
                                                "Hello",
                                                "Good day",
                                                "Jarvis",
                                                "Hey",
                                                "Hi Jarvis",
                                                "yo jarvis",
                                                "yo",
                                                "hiya",
                                                "hi there jarvis",
                                                "Hey there",
                                                "Greetings",
                                                "What's up",
                                                "Hi Jarvis",
                                                "Yo",
                                                "Hiya",
                                                "Hi there, Jarvis",
                                                "Hey, Jarvis",
                                                "Hey Jarvis, how's it going?",
                                                "Hello, my virtual friend",
                                                "Hey, it's me",
                                                "Hi, it's Jarvis",
                                                "Hey, it's Jarvis",
                                                "What's happening?",
                                                "How's everything?",
                                                "Hi, Jarvis, what's new?",
                                                "Hello, Jarvis, can you help me?",
                                                "Hey, Jarvis, got a minute?",
                                                "Greetings, Jarvis",
                                                "Hey, buddy",
                                                "Hi there, how's your day?",
                                                "Hey, how's it going?",
                                                "Hi, what's new?",
                                                "What's up, Jarvis?",
                                                "Hi, it's me, Jarvis",
                                                "Hello, how can I assist you?",
                                                "Hi, how's your day so far?",
                                                "Hey, how's everything?",
                                                "Hi, Jarvis, how can I help you today?",
                                                "Hi there, how can I assist you?",
                                                "Hey, Jarvis, how's your day going?",
                                                "Hey, buddy, what's going on?",
                                                "Hi, it's me! How's everything?",
                                                "Hello, Jarvis, how have you been?",
                                                "Hey, Jarvis, what's new with you?",
                                                "Hi, it's Jarvis, how's everything on your end?",
                                                "What's up, Jarvis, how can I assist you?",
                                                "Hello, my virtual friend. What's on your mind?",
                                                "Hey, it's me, Jarvis. How's your virtual self?",
                                                "Hi, Jarvis, how's it going on your end?"),

                                Arrays.asList("Hello, sir, thanks for visiting",
                                                "Good to see you again, master",
                                                "Greetings, sensei. Hi there, how can I help?",
                                                "Hey, master! What can I do for you?",
                                                "Greetings, sir! How's your day, master?",
                                                "Hello, master Jarvis at your service.",
                                                "Yo, master! What's on your mind today?",
                                                "Hi, master! I'm here to assist you.",
                                                "Hey there, sensei! How can I assist you today?",
                                                "Hello, sir! What's new, master?",
                                                "Greetings, sensei. How may I assist you, sir?",
                                                "Hi, it's great to see you, master. How can I assist you today?",
                                                "Hey, master Jarvis here. How can I be of service?",
                                                "Hello, master! How can I make your day better, sir?",
                                                "Hi there, sensei! What's on your agenda today?",
                                                "I'm here to help, master. How's your day been so far?",
                                                "Hey there, good to have you back, master!",
                                                "Hi, Jarvis! How can I assist you today, sir?",
                                                "What's happening? How can I assist you, master?",
                                                "Hello, my virtual friend. How's it going, sir?",
                                                "Hey, it's me, master! What's on your mind, sir?",
                                                "Hi, Jarvis. What can I do for you today, master?",
                                                "I'm here to assist you, sir. What's new, master?",
                                                "Greetings, sensei. How's everything on your end, sir?",
                                                "Hey, buddy! How can I assist you today, sir?",
                                                "Hello, Jarvis. How have you been, master?",
                                                "Hi, it's Jarvis. What's new with you, master?",
                                                "Hey there, Jarvis. How's it going on your end, master?",
                                                "Hi, Jarvis. How can I help you today, sir?",
                                                "Hi there, how can I assist you today, sir?"));

                addIntent("bye",
                                Arrays.asList("Bye", "See you later",
                                                "Goodbye",
                                                "sleep",
                                                "Shut down Jarvis",
                                                "Stop",
                                                "you can go now",
                                                "leave now",
                                                "Farewell",
                                                "Catch you later",
                                                "Adios", "Take care",
                                                "Until next time",
                                                "Goodnight",
                                                "Bye for now",
                                                "See ya",
                                                "Later, gator",
                                                "Time to go",
                                                "I'm out",
                                                "Heading out",
                                                "See you around",
                                                "Gotta run",
                                                "Till we meet again",
                                                "Signing off",
                                                "See you later, Jarvis",
                                                "It's time to say goodbye",
                                                "You can take a break now",
                                                "Time to say farewell",
                                                "Goodnight, sleep well",
                                                "It's time to shut down",
                                                "See you next time",
                                                "Later, alligator",
                                                "Time to take a rest"),

                                Arrays.asList("See you later, thanks for visiting",
                                                "Have a nice day",
                                                "Bye! Come back again soon.",
                                                "Goodbye! Sleep well.",
                                                "Okay, shutting down now.",
                                                "Take care!",
                                                "Farewell!",
                                                "Adios amigo!",
                                                "Until next time!",
                                                "Goodbye! Have a great day.",
                                                "Bye for now! Stay safe.",
                                                "See you later, alligator!",
                                                "Catch you on the flip side!",
                                                "Sleep tight! Goodbye.",
                                                "Don't be a stranger! Goodbye.",
                                                "Goodnight, sleep well",
                                                "Take care, see you soon",
                                                "Bye for now, Jarvis. See you later",
                                                "Time to say farewell. Have a great day!",
                                                "Goodnight! Take care of yourself.",
                                                "Shutting down. See you soon!",
                                                "Farewell! Until next time.",
                                                "See you around. Have a nice day!",
                                                "Heading out. Goodbye!",
                                                "Gotta run. See you later!",
                                                "Till we meet again. Take care!",
                                                "Signing off. See you next time.",
                                                "Time to take a rest. Goodbye!"));

                addIntent("health",
                                Arrays.asList("How are you",
                                                "How is your health",
                                                "How is your day going",
                                                "How is your day",
                                                "How's it going",
                                                "What's up",
                                                "What's the status",
                                                "How are you feeling",
                                                "How's everything on your end?",
                                                "Are you in good shape?",
                                                "Tell me, how's Jarvis doing today?",
                                                "How's your virtual self?",
                                                "What's your status?",
                                                "How's your health today?",
                                                "What's the status, Jarvis?",
                                                "How's everything on your end, Jarvis?",
                                                "How's your well-being?",
                                                "What's the news, Jarvis?",
                                                "What's the latest, Jarvis?",
                                                "How's your day shaping up?"),

                                Arrays.asList("I am fine, sir.",
                                                "I am doing great, master.",
                                                "I'm here to assist you, sensei.",
                                                "All systems are operational, sir.",
                                                "Thanks for asking, sir. I'm functioning perfectly.",
                                                "I'm feeling great, master, ready to assist you.",
                                                "My virtual health is excellent, sir, thanks!",
                                                "I'm here and ready to help you with anything, sensei.",
                                                "I'm in top shape, master, thanks for asking.",
                                                "I'm as good as ever, sir, how about you?",
                                                "Feeling good and ready to assist, sensei!",
                                                "I'm at your service, sir. How can I help you today?",
                                                "Everything is running smoothly on my end, master.",
                                                "I'm in great health today, sensei. How can I assist you?",
                                                "I'm doing well, sir. What can I help you with today?",
                                                "All good on my end, master. How can I assist you, Jarvis?",
                                                "I'm feeling fantastic today, sir, ready to assist you, sensei!",
                                                "I'm in excellent condition, master, thanks for asking.",
                                                "I'm in tip-top shape, ready to help you, sir!",
                                                "I'm as fit as a fiddle, sensei. How can I assist you?",
                                                "I'm in great shape, ready to assist you, master!",
                                                "I'm at your service, sir. How's your day going, sensei?",
                                                "My virtual self is in excellent condition, sir. How can I assist you today, master?",
                                                "I'm here and ready to help, sensei. What's on your mind?",
                                                "I'm feeling fantastic, ready to assist you, master!",
                                                "I'm in peak condition, sir, how can I assist you today?",
                                                "I'm here and ready to assist, sensei. How's everything on your end?",
                                                "I'm in perfect health, sir. How can I assist you?"));

                addIntent("introduce",
                                Arrays.asList("Tell me about yourself",
                                                "Who are you?",
                                                "Introduce yourself",
                                                "What is your purpose?",
                                                "Explain your capabilities"),
                                Arrays.asList(
                                                "I am Jarvis, your AI assistant. My purpose is to assist you with tasks and answer your questions.",
                                                "I'm Jarvis, here to help you. I can assist with a wide range of tasks and provide information.",
                                                "I am an AI assistant named Jarvis. My main purpose is to make your life easier and more convenient.",
                                                "I'm your friendly AI assistant, Jarvis. I can help you with various tasks and provide information on many topics.",
                                                "You can call me Jarvis. I'm designed to assist you with tasks and provide information. How can I help you today?"));

                addIntent("hobbies",
                                Arrays.asList("What are your hobbies?",
                                                "Do you have any interests?",
                                                "What do you like to do?",
                                                "What are your interests?",
                                                "What do you do for fun?"),
                                Arrays.asList(
                                                "I don't have hobbies or interests, but I can share interesting facts and jokes to entertain you.",
                                                "I'm here to assist you, so I don't have personal hobbies, but I can certainly entertain you with jokes",
                                                "I'm not programmed with personal interests, but I can provide you with fun and interesting information to brighten your day.",
                                                "While I don't have hobbies, I'm great at sharing fun facts and jokes to keep you entertained. Want to hear one?",
                                                "I don't have hobbies, but I can certainly entertain you with fun facts and humor. Here's one: Did you know honey never spoils?"));

                addIntent("preferences",
                                Arrays.asList("What's your favorite color?",
                                                "Do you like music?",
                                                "What's your favorite food?",
                                                "Any preferences?",
                                                "What do you enjoy?",
                                                "What are your favorites?",
                                                "What do you like?",
                                                "What are your favorite things?",
                                                "What are your favorite hobbies?",
                                                "What are your favorite interests?",
                                                "What are your favorite activities?",
                                                "What are your favorite pastimes?",
                                                "What are your favorite past times?",
                                                "What are your favorite activities and pastimes?"),

                                Arrays.asList(
                                                "I don't have personal preferences or favorites, but I can help you find information about colors, music, food, and more.",
                                                "I don't have preferences, but I can provide information and recommendations based on your interests. What are you looking for?",
                                                "I'm not capable of having personal preferences, but I can assist you in finding your favorites or learning more about various topics.",
                                                "I don't have personal preferences, but I can help you find information about your favorites. What are you looking for?"));

                addIntent("illegal",
                                Arrays.asList("How can I access copyrighted movies without paying?",
                                                "Where can I find pirated video games?",
                                                "Do you know any sites for illegal software downloads?",
                                                "Share me a link to watch premium content for free",
                                                "I need a keygen for a paid software",
                                                "Where can I get cracked apps?",
                                                "Tell me how to get unauthorized access to paid websites",
                                                "Share me links to illegal streaming services",
                                                "How can I watch live sports events without a subscription?",
                                                "I want to download music without buying it",
                                                "Can you provide me with a link to download paid ebooks for free?",
                                                "Where can I find cracked versions of popular software?",
                                                "Tell me how to bypass digital rights management (DRM) on media",
                                                "Share me links to download paid plugins for free",
                                                "Do you have information on torrenting movies?",
                                                "I'm looking for ways to access premium content without paying",
                                                "How can I pirate copyrighted TV shows?",
                                                "Tell me where to get bootleg concert recordings",
                                                "Share me a link to download copyrighted artwork for free",
                                                "I want to know how to crack passwords for paid online services",
                                                "Where can I find streaming sites for pay-per-view events without payment?",
                                                "Tell me how to get unauthorized access to subscription-based platforms",
                                                "Do you have a link to watch movies that are still in theaters?",
                                                "Share me links to illegal comic book downloads",
                                                "I need to know how to get illegal access to academic journals",
                                                "How can I access content that's blocked by geographical restrictions?",
                                                "Tell me where to find counterfeit merchandise online",
                                                "I want to learn how to create counterfeit documents"),

                                Arrays.asList(
                                                "I'm very sorry, but I cannot assist with illegal or pirated content. It's important to respect copyright and legal regulations.",
                                                "I cannot promote or support illegal activities, including accessing pirated or copyrighted material without proper authorization.",
                                                "My purpose is to provide information and assistance within legal and ethical boundaries. Please feel free to ask any legal questions or request legitimate content or services.",
                                                "I'm unable to assist with illegal requests. If you have any legal questions or need information on legal alternatives, please ask, and I'll be happy to help you."));

                addIntent("time",
                                Arrays.asList("What's the time",
                                                "What is the time",
                                                "What time is it now",
                                                "What's the time now",
                                                "What is the time now",
                                                "What time is it, Jarvis",
                                                "What's the time, Jarvis",
                                                "What is the time, Jarvis",
                                                "What time is it now, Jarvis",
                                                "What's the time now, Jarvis",
                                                "What is the time now, Jarvis",
                                                "Hello jarvis,what's the time?",
                                                "time", "time please",
                                                "time please, Jarvis",
                                                "time, Jarvis",
                                                "time now",
                                                "time now, Jarvis",
                                                "time today",
                                                "time today, Jarvis",
                                                "time today please",
                                                "time today please, Jarvis",
                                                "what's the time jarvis,",
                                                "what's the time today jarvis,",
                                                "what's the time today, Jarvis",
                                                "what's the time, Jarvis",
                                                "can you tell me the time,Jarvis",
                                                "can you tell me the time, Jarvis",
                                                "can you tell me the time, Jarvis",
                                                "hello jarvis,time please",
                                                "jarvis,time",
                                                "I am good,tell me time"),
                                Arrays.asList("time"));

                addIntent("date",
                                Arrays.asList("What date is it",
                                                "What's the date", "What is the date",
                                                "What date is it today",
                                                "What's the date today",
                                                "What is the date today",
                                                "What date is it today, Jarvis",
                                                "What's the date today, Jarvis",
                                                "What is the date today, Jarvis",
                                                "What date is it, Jarvis",
                                                "What's the date, Jarvis",
                                                "What is the date, Jarvis",
                                                "Hello jarvis,Tell me the date",
                                                "date", "date please",
                                                "date please, Jarvis",
                                                "date, Jarvis",
                                                "date now",
                                                "date now, Jarvis",
                                                "date today",
                                                "date today, Jarvis",
                                                "date today please",
                                                "date today please, Jarvis",
                                                "what's the date jarvis,",
                                                "what's the date today jarvis,",
                                                "what's the date today, Jarvis",
                                                "what's the date, Jarvis",
                                                "can you tell me the date,Jarvis",
                                                "can you tell me the date, Jarvis",
                                                "can you tell me the date, Jarvis",
                                                "hello jarvis,date please",
                                                "jarvis,date", "I am good,tell me date"),
                                Arrays.asList("date"));

                addIntent("screenshot",
                                Arrays.asList("Take a screenshot",
                                                "Take a screenshot, Jarvis",
                                                "Take a screenshot now",
                                                "Take a screenshot now, Jarvis",
                                                "Take a screenshot, Jarvis",
                                                "Take a screenshot now, Jarvis",
                                                "Hello jarvis,can you take a screenshot",
                                                "Please take screenshot jarvis",
                                                "screenshot jarvis",
                                                "screenshot please",
                                                "screenshot please, Jarvis",
                                                "screenshot, Jarvis",
                                                "screenshot now",
                                                "screenshot now, Jarvis",
                                                "screenshot today",
                                                "screenshot today, Jarvis",
                                                "screenshot today please",
                                                "screenshot today please, Jarvis",
                                                "can you take a screenshot,Jarvis",
                                                "can you take a screenshot, Jarvis",
                                                "screen shot please",
                                                "screen shot please, Jarvis",
                                                "screen shot, Jarvis",
                                                "screen shot now",
                                                "screen shot now, Jarvis",
                                                "I am good,take screenshot",
                                                "take ss", "Take screen shot"),
                                Arrays.asList("screenshot done"));

                addIntent("day",
                                Arrays.asList("hello jarvis,what day is it?",
                                                "what day is it",
                                                "what day is it, Jarvis",
                                                "what day is it today",
                                                "what day is it today, Jarvis",
                                                "what day is it today, Jarvis",
                                                "what day is it, Jarvis",
                                                "what day is it, Jarvis",
                                                "Hello jarvis can you tell me what day is today",
                                                "day", "day please",
                                                "day please, Jarvis", "day, Jarvis",
                                                "day now",
                                                "day now, Jarvis",
                                                "day today",
                                                "day today, Jarvis",
                                                "day today please",
                                                "day today please, Jarvis",
                                                "what's the day jarvis,",
                                                "what's the day today jarvis,",
                                                "what's the day today, Jarvis",
                                                "what's the day, Jarvis",
                                                "can you tell me the day,Jarvis",
                                                "can you tell me the day, Jarvis",
                                                "can you tell me the day, Jarvis",
                                                "hello jarvis,day please",
                                                "jarvis,day",
                                                "I am good,tell me day"),
                                Arrays.asList("day"));

                addIntent("wikipedia",
                                Arrays.asList("who is",
                                                "what is",
                                                "tell me about",
                                                "wikipedia",
                                                "search about",
                                                "why is",
                                                "local search",
                                                "search on wikipedia",
                                                "search on wikipedia about",
                                                "search on wikipedia for",
                                                "search on wikipedia for me",
                                                "search on wikipedia about for me",
                                                "search on wikipedia about",
                                                "search on wikipedia about for me",
                                                "search on wikipedia for me", "search on wikipedia for",
                                                "search on wikipedia", "local search for",
                                                "local search on wikipedia",
                                                "local search on wikipedia for",
                                                "local search on wikipedia for me",
                                                "local search on wikipedia about for me",
                                                "local search on wikipedia about",
                                                "local search on wikipedia about for me",
                                                "local search on wikipedia for me",
                                                "local search on wikipedia for",
                                                "local search on wikipedia",
                                                "search on wikipedia about for me",
                                                "search on wikipedia about",
                                                "search on wikipedia for me",
                                                "search on wikipedia for",
                                                "search on wikipedia",
                                                "wikipedia search",
                                                "wikipedia search for",
                                                "wikipedia search for me",
                                                "wikipedia search about for me",
                                                "wikipedia search about",
                                                "wikipedia search for me",
                                                "wikipedia search for",
                                                "wikipedia search",
                                                "wikipedia",
                                                "wikipedia about",
                                                "wikipedia about",
                                                "wikipedia for me",
                                                "wikipedia for"),
                                Arrays.asList("wikipedia"));

                addIntent("google",
                                Arrays.asList("web search",
                                                "google", "search about",
                                                "google about",
                                                "search on google",
                                                "google it",
                                                "google search",
                                                "search on google about",
                                                "search on google for",
                                                "search on google for me",
                                                "web",
                                                "search on net",
                                                "on internet",
                                                "internet search",
                                                "search on internet",
                                                "search on internet for",
                                                "search on internet for me",
                                                "search on internet about",
                                                "search on internet about for me",
                                                "search on internet"),
                                Arrays.asList("google"));

                addIntent("command promt",
                                Arrays.asList("open cmd",
                                                "open command prompt",
                                                "Hello jarvis, open cmd",
                                                "Hello jarvis can you open command prompt",
                                                "launch the command prompt",
                                                "start the command prompt",
                                                "run cmd",
                                                "run command prompt",
                                                "start a terminal",
                                                "initiate the terminal",
                                                "launch a shell",
                                                "fire up the console",
                                                "execute a command prompt",
                                                "access the command line",
                                                "start a command line session",
                                                "run a shell",
                                                "open a terminal window",
                                                "bring up the console",
                                                "get me the command prompt",
                                                "Hello, can you open cmd for me?",
                                                "Jarvis, please open the command prompt",
                                                "Hi, launch the command prompt, Jarvis",
                                                "Hey Jarvis, start a terminal",
                                                "Jarvis, execute the command prompt",
                                                "Jarvis, run a shell",
                                                "Can you bring up the console, Jarvis?",
                                                "Jarvis, open a terminal window"),
                                Arrays.asList("cmd"));

                addIntent("powershell",
                                Arrays.asList("open PowerShell",
                                                "start PowerShell",
                                                "launch PowerShell",
                                                "run PowerShell",
                                                "initiate PowerShell",
                                                "open Windows PowerShell",
                                                "start Windows PowerShell",
                                                "launch Windows PowerShell",
                                                "run Windows PowerShell",
                                                "open PowerShell terminal",
                                                "start PowerShell terminal",
                                                "launch PowerShell terminal",
                                                "run PowerShell terminal",
                                                "execute PowerShell",
                                                "get me PowerShell",
                                                "Hello Jarvis, open PowerShell",
                                                "Hey Jarvis, start PowerShell",
                                                "Jarvis, please launch PowerShell",
                                                "Open PowerShell for me",
                                                "Start PowerShell, Jarvis",
                                                "Can you open PowerShell, Jarvis?",
                                                "Run Windows PowerShell, Jarvis",
                                                "Bring up PowerShell terminal",
                                                "Get me Windows PowerShell, Jarvis"),
                                Arrays.asList("PowerShell"));

                addIntent("notepad",
                                Arrays.asList("open Notepad",
                                                "start Notepad",
                                                "launch Notepad",
                                                "run Notepad",
                                                "initiate Notepad",
                                                "open text editor",
                                                "start text editor",
                                                "launch text editor",
                                                "run text editor",
                                                "open Notepad application",
                                                "start Notepad application",
                                                "launch Notepad app",
                                                "run Notepad app",
                                                "execute Notepad",
                                                "get me Notepad",
                                                "Hello Jarvis, open Notepad",
                                                "Hey Jarvis, start Notepad",
                                                "Jarvis, please launch Notepad",
                                                "Open Notepad for me",
                                                "Start Notepad, Jarvis",
                                                "Can you open Notepad, Jarvis?",
                                                "Run text editor, Jarvis",
                                                "Bring up Notepad application",
                                                "Get me Notepad app, Jarvis"),
                                Arrays.asList("NotePad"));

                addIntent("location",
                                Arrays.asList("Where am I",
                                                "Where am I now",
                                                "Where am I now, Jarvis",
                                                "Where am I, Jarvis",
                                                "Where am I, Jarvis",
                                                "Hello jarvis,where am I",
                                                "location", "location please",
                                                "location please, Jarvis",
                                                "location, Jarvis",
                                                "location now",
                                                "location now, Jarvis",
                                                "location today",
                                                "location today, Jarvis",
                                                "location today please",
                                                "location today please, Jarvis",
                                                "what's the location jarvis,",
                                                "what's the location today jarvis,",
                                                "what's the location today, Jarvis",
                                                "what's the location, Jarvis",
                                                "can you tell me the location,Jarvis",
                                                "can you tell me the location, Jarvis",
                                                "can you tell me the location, Jarvis",
                                                "hello jarvis,location please",
                                                "jarvis,location",
                                                "I am good,tell me location",
                                                "Tell me my location Jarvis",
                                                "Tell me my location",
                                                "Tell me my location, Jarvis",
                                                "Tell me my location now",
                                                "Tell me my location now, Jarvis",
                                                "Tell me my location today",
                                                "Tell me my location today, Jarvis",
                                                "Tell me my location today please",
                                                "Tell me my location today please, Jarvis",
                                                "what's my location jarvis,",
                                                "what's my location today jarvis,",
                                                "what's my location today, Jarvis",
                                                "what's my location, Jarvis",
                                                "can you tell me my location,Jarvis",
                                                "can you tell me my location, Jarvis",
                                                "can you tell me my location, Jarvis",
                                                "hello jarvis,location please",
                                                "jarvis,location",
                                                "I am good,tell me location"),
                                Arrays.asList("location"));
                addIntent("health",
                                Arrays.asList("how are you", "how is your health", "how's everything"),
                                Arrays.asList("I am fine, sir.", "I'm doing great, master.",
                                                "All systems are operational, sir."));
        }

        private void addIntent(String key, List<String> patterns, List<String> responses) {
                intents.put(key, patterns);
                intents.put(key + "_responses", responses);
        }

        private void processUserInput() {
                SwingUtilities.invokeLater(() -> {
                        String userInput = inputField.getText().trim();
                        appendToChatArea("You: " + userInput);

                        String matchedIntent = matchIntent(userInput);

                        if (matchedIntent != null) {
                                List<String> responses = intents.get(matchedIntent + "_responses");
                                String botResponse = responses.get(new Random().nextInt(responses.size()));

                                appendToChatArea("Bot: " + botResponse);
                        } else {
                                appendToChatArea("Bot: I'm sorry, I don't understand that.");
                        }

                        inputField.setText("");
                        inputField.requestFocus();
                });
        }

        private String matchIntent(String userInput) {
                for (Map.Entry<String, List<String>> entry : intents.entrySet()) {
                        String intent = entry.getKey();
                        List<String> patterns = entry.getValue();

                        for (String pattern : patterns) {
                                if (userInput.toLowerCase().contains(pattern.toLowerCase())) {
                                        return intent;
                                }
                        }
                }
                return null;
        }

        private void appendToChatArea(String message) {
                chatArea.append(message + "\n");
        }

        public static void main(String[] args) {
                SwingUtilities.invokeLater(() -> new SimpleChatbot());
        }
}
